version: '3.8'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp_vol:/var/www/html
    restart: always
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wp_vol:/var/www/html
    env_file: .env
    networks:
      - inception_network
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
         - DB_NAME=${MYSQL_DATABASE}
         - DB_USER=${MYSQL_USER}
         - DB_PASSWORD=${MYSQL_PASSWORD}
         - DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - inception_network
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: unless-stopped

networks:
  inception_network:

volumes:
  wp_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/kali/data/wordpress"
  mariadb_vol:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: "/home/kali/data/db"
